parameters:
  
services:
  gift_wrapping_handler:
    class: Heystack\GiftWrapping\GiftWrappingHandler
    arguments: [ @state, @event_dispatcher, @currency_service ]
    calls:
      - [ restoreState ]
    tags:
      - { name: ss_orm_backend.data_provider }
      - { name: transaction.modifier }

  gift_wrapping_subsriber:
    class: Heystack\GiftWrapping\Subscriber
    arguments: [ @event_dispatcher, @gift_wrapping_handler ]
    tags:
      - { name: event_dispatcher.subscriber }
      
  gift_wrapping_transaction_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-giftwrapping/config/storage/gift_wrapping_transaction.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }
      
  gift_wrapping_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-giftwrapping/config/storage/gift_wrapping.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema, reference: true }
      